### ISSUE TITLE
Courses page : Space between each post should be 54px, currently it is 108px

### ISSUE THREAD

**Issue by ravi-josyula** [titan-cebu/Nicole-O-Neill-Kinesiology#11]
![2016-04-07_1356](https://cloud.githubusercontent.com/assets/13309806/14346333/62cfa3a8-fccf-11e5-9ff6-3821cd5e772b.png)

**Comment by Santosh-titan** [comment]
Space between each item will change based on content, because paragraphs,  ordered list and headers have different margins.
