### ISSUE TITLE
General : Line spacing should be reduces

### ISSUE THREAD

**Issue by ravi-josyula** [titan-cebu/Nicole-O-Neill-Kinesiology#12]
![2016-04-07_1355](https://cloud.githubusercontent.com/assets/13309806/14346514/36f906a6-fcd0-11e5-9d17-b686bc418620.png)
![1](https://cloud.githubusercontent.com/assets/13309806/14346529/42b206c8-fcd0-11e5-8165-3ab1efe0d569.png)

**Comment by Santosh-titan** [comment]
It is not possible to design as per PSD, because it coming from post content as we can't target specific element form post content.
