### ISSUE TITLE
Admin(Form Notifications) : Contact Email should be entered

### ISSUE THREAD

**Issue by ravi-josyula** [titan-cebu/Nicole-O-Neill-Kinesiology#5]
Applicable to 'Contact Us', 'Contact Us Today' and 'Home Contact Form'
![9](https://cloud.githubusercontent.com/assets/13309806/14342418/32b11f52-fcb7-11e5-8412-d2807671d0e8.png)

**Comment by Santosh-titan** [comment]
To email id has already given in admin general settings, so I think no need to enter for each form.
